// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDaPe4CG7RY69HYRz5AD4YlhS4P0jLxS0',
    appId: '1:399513936329:web:9a9151ac21d3d33a974818',
    messagingSenderId: '399513936329',
    projectId: 'fasum-apps1',
    authDomain: 'fasum-apps1.firebaseapp.com',
    storageBucket: 'fasum-apps1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZYHaQ5nGoQsQUKllV9QkCEtMgsWwaB4',
    appId: '1:399513936329:android:b5ae552932598563974818',
    messagingSenderId: '399513936329',
    projectId: 'fasum-apps1',
    storageBucket: 'fasum-apps1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDaPe4CG7RY69HYRz5AD4YlhS4P0jLxS0',
    appId: '1:399513936329:web:83d96ae535d33ec1974818',
    messagingSenderId: '399513936329',
    projectId: 'fasum-apps1',
    authDomain: 'fasum-apps1.firebaseapp.com',
    storageBucket: 'fasum-apps1.firebasestorage.app',
  );
}
