// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKlRTm_MdkpqnBG9SikKl9hnTCU_yN0zI',
    appId: '1:1075500144185:web:46ad958a5dc0587c141fe8',
    messagingSenderId: '1075500144185',
    projectId: 'first-app-ca4e1',
    authDomain: 'first-app-ca4e1.firebaseapp.com',
    databaseURL: 'https://first-app-ca4e1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-ca4e1.firebasestorage.app',
    measurementId: 'G-0D5DKSP6JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_0x0O8VHAdh7xo0yP_kNfLSuG70Y1E-A',
    appId: '1:1075500144185:android:2d018e0b438d486c141fe8',
    messagingSenderId: '1075500144185',
    projectId: 'first-app-ca4e1',
    databaseURL: 'https://first-app-ca4e1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-ca4e1.firebasestorage.app',
  );
}
